### ISSUE TITLE
Add your contact info - maybe in Wiki?

### ISSUE THREAD

**Issue by GLMeece** [nickjj/build-a-saas-app-with-flask#14]
I am really looking forward to the official launch. In the meantime, perhaps you could put links to:

* The [project page](http://buildasaaswithflask.com/).
* Your [home page](http://nickjanetakis.com/).
* Your [blog](http://blog.nickjanetakis.com/).
* This [repo](https://github.com/nickjj/build-a-saas-app-with-flask/).

:smiley:

**Comment by nickjj** [comment]
Thanks. I haven't given much thought yet to what will go on the wiki. I imagine sometime down the line it will be a community driven knowledge resource. I'm not sure if the wiki is the best place to put my personal info, maybe a tiny segment at the bottom of the readme works?

The project's main home page (readme) and my contact details (license) currently contains some of the info you have gathered but I agree, it can be tricky to find those links because they are not labeled.

**Comment by nickjj** [comment]
After nearly a year I think it's safe to say this can be closed!

I will be completely re-vamping this project in the near future and the documentation / accumulation of information will be better for people who are only interested in the open source version.
