### ISSUE TITLE
rEQUEST fOR fEATURE: sUPPORT doge oUT oF tHE bOX

### ISSUE THREAD

**Issue by machinacarta** [nickjj/build-a-saas-app-with-flask#23]
TO THE MOON

**Comment by machinacarta** [comment]
https://my.dogechain.info

**Comment by nickjj** [comment]
Hello,

I think crypto currencies definitely have a future and I'd certainly be ok with adding a dogecoin payment processing gateway, but a number of technical issues need to be addressed first.

Currently the billing system is mostly coupled to Stripe because Stripe offers support for a ton of functionality out of the box. Step 1 would be to create a payment gateway abstraction, and then start implementing custom backends.

I don't think something of this magnitude will make it in the screencast series / initial version but it's something that may happen down the road.

**Comment by scott91e1** [comment]
aS a lEARING tROOL fOR aN eXAMPLE app aMOUNG kids
nOT eXACTLY sTRIPES cORE "business"
let the kids rule DOGE :)
TO THE MOON!

**Comment by machinacarta** [comment]
suggestion:
  make the guys who want stripe 
  subscribe at the corporate level

**Comment by nickjj** [comment]
Closing this as there's an entirely new code base. Definitely keeping this mind tho!
