### ISSUE TITLE
Add loadbalancers in front of docker images to support scaling of different tiers

### ISSUE THREAD

**Issue by LubergAlexander** [nickjj/build-a-saas-app-with-flask#8]
It would be great to add an LB infront of web & db services in order to use docker scaling functionality docker-compose scale web=2 , docker-compose scale db=3

**Comment by nickjj** [comment]
I haven't created Docker images yet for the web app and celery worker. It is on the horizon. Currently I'm just launching them with honcho because it allows us to attach a debugger to it much easier.

I wouldn't use `docker-compose` in production btw. It's not ready for that IMO. It is great for development though.

**Comment by LubergAlexander** [comment]
yeah they are in alpha now AFAIK, are you planning to use something else to control the fleet of containers?

**Comment by nickjj** [comment]
I planned to keep things simple in the screencast series by just putting everything on a single host. On a host with an SSD you'd be surprised at how far you can get. Supporting hundreds of users is very achievable without breaking the bank.

The host OS will be CoreOS which has solutions available for multi-host cluster management. Maybe in a few months Kubernetes will be ready to rock for prime time too.

**Comment by nickjj** [comment]
Going to close this because the production deploy info will be contained in a different repo. Thanks for the feedback.
